# A first workflow to play around with the editor
name: My first Workflow
on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  first_job:
    name:  My first job
    runs-on: ubuntu-latest
    steps: 
       - run: |
           echo "Hello world from dawone"
       - name: Checkout
         uses: actions/checkout@v4.2.2
       - name: list directory contents 
         run: tree 
  
          
  
